#!/usr/bin/env python3

import sys
import os
from analyzer import Analyzer
import helpers
from termcolor import colored

def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets screen_name_for_user_on_twitter")

    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # set screen_name
    screen_name = sys.argv[1].strip('@')

    # queries Twitter's API for user's most recent 50 tweets
    tweets = helpers.get_user_timeline(screen_name, 50)

    # if screen_name doesn't exist, return error
    if tweets == None:
        sys.exit("User is private or doesn't exist")

    for tweet in tweets:
        score = analyzer.analyze(sys.argv[1])
    if score > 0.0:
        print(colored("{} {}".format(score, tweet), "green"))
    elif score < 0.0:
        print(colored("{} {}".format(score, tweet), "red"))
    else:
        print(colored("{} {}".format(score, tweet), "yellow"))

if __name__ == "__main__":
    main()
